### PR TITLE
Add User Persona

### PR DESCRIPTION
**Pull request by ClaraLopezUribe**
Add to the Reader/Guest to the User Persona list.
A Reader/Guest are those using the website only to read testimonials.  Future features for this persona may be to like comments or save testimonials for future reference.

### CODE REVIEW

**Comment by roberto-morado** [comment]
This looks great; could you just change your base branch to `develop` instead of `main`

**Review by roberto-morado — COMMENTED** [review]
Change your base branch to `develop` instead of `main`

**Review by roberto-morado — CHANGES_REQUESTED** [review]
Use `develop` branch to merge all changes

**Comment by ClaraLopezUribe** [comment]
Thanks Roberto!  

I created and switched to develop branch on my fork.  Do I need to close this pull request and request a new one using the develop branch?

**Review by roberto-morado — APPROVED** [review]

**Comment by roberto-morado** [comment]
Hey @ClaraLopezUribe, this pr is ready to merge; however as a right now:

# This pr is blocked by #19 

There are some file changes that have not yet being merged to the develop branch, I'm waiting for @thisisazeez to merge #19 as I ask him to review the code; he's a more experienced back end developer and I'd like to make sure what I did is correct.

After #19 have been merged you can merge this pr as well

**Comment by roberto-morado** [comment]
This are the changes I'm talking about: ef716f9bb44d6ec8285073b41143116082ce09db

**Pull request merged**
